name: Drift Correction

on:
  workflow_dispatch:

jobs:
  drift-correction-dev:
    name: Drift Correction Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infrastructure/dev
        shell: bash -e {0} # Ensures scripts exit on error

    permissions:
      id-token: write
      contents: read
      pull-requests: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE_NAME }}"
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: "1.9.2" # Or "latest"
          terraform_wrapper: false

      - name: Install jq
        run: |
          set -x
          sudo apt-get update && sudo apt-get install -y jq
          which jq

      - name: Verify Terraform Version & Capture Path
        id: verify_tf
        run: |
          set -x
          echo "Verifying Terraform version and path:"
          TF_PATH=$(which terraform)
          echo "Terraform binary path is: $TF_PATH"
          echo "terraform_path=$TF_PATH" >> "$GITHUB_OUTPUT"
          $TF_PATH version

      - name: Terraform Init
        id: init
        run: |
          set -x
          ${{ steps.verify_tf.outputs.terraform_path }} init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE_DEV }}"

      # First Plan Step (Before Imports)
      - name: Terraform Plan Before Imports
        id: plan_before_imports
        run: |
          set -x
          echo "--- Plan Before Imports Step ---"
          ${{ steps.verify_tf.outputs.terraform_path }} plan \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            -no-color

      - name: Terraform Import Login
        id: import-login
        run: |
          set -x
          TF_PATH=${{ steps.verify_tf.outputs.terraform_path }}
          echo "--- Import Login Step ---"
          echo "Using Terraform binary at: $TF_PATH"

          echo "Getting REST_API_ID..."
          STATE_JSON=$($TF_PATH show -json)
          echo "State JSON fetched via 'show -json'."

          REST_API_ID=$(echo "$STATE_JSON" | jq -r '.values.root_module.child_modules[] | select(.address=="module.api") | .resources[] | select(.address=="module.api.aws_api_gateway_rest_api.api") | .values.id')
          echo "REST_API_ID is: [${REST_API_ID}]"

          if [ -z "$REST_API_ID" ] || [ "$REST_API_ID" == "null" ]; then
            echo "::error::REST_API_ID not found in state JSON or is empty. Cannot proceed."
            echo "Full state JSON:"
            echo "$STATE_JSON"
            exit 1
          fi

          echo "Getting LOGIN_RESOURCE_ID..."
          LOGIN_RESOURCE_ID=$(aws apigateway get-resources --rest-api-id $REST_API_ID --query "items[?path=='/login'].id" --output text)
          echo "LOGIN_RESOURCE_ID is: [${LOGIN_RESOURCE_ID}]"
          
          if [ -z "$LOGIN_RESOURCE_ID" ]; then
            echo "::error::LOGIN_RESOURCE_ID is empty. Cannot proceed."
            exit 1
          fi

          echo "Running terraform import..."
          $TF_PATH import \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            module.api.aws_api_gateway_resource.login $REST_API_ID/$LOGIN_RESOURCE_ID

      - name: Terraform Import Get Upload URL
        id: import-get-upload-url
        run: |
          set -x
          TF_PATH=${{ steps.verify_tf.outputs.terraform_path }}
          echo "--- Import Get Upload URL Step ---"
          echo "Using Terraform binary at: $TF_PATH"

          echo "Getting REST_API_ID..."
          STATE_JSON=$($TF_PATH show -json)
          echo "State JSON fetched via 'show -json'."
          
          REST_API_ID=$(echo "$STATE_JSON" | jq -r '.values.root_module.child_modules[] | select(.address=="module.api") | .resources[] | select(.address=="module.api.aws_api_gateway_rest_api.api") | .values.id')
          echo "REST_API_ID is: [${REST_API_ID}]"

          if [ -z "$REST_API_ID" ] || [ "$REST_API_ID" == "null" ]; then
            echo "::error::REST_API_ID not found in state JSON or is empty. Cannot proceed."
            echo "Full state JSON:"
            echo "$STATE_JSON"
            exit 1
          fi

          echo "Getting GET_UPLOAD_URL_RESOURCE_ID..."
          GET_UPLOAD_URL_RESOURCE_ID=$(aws apigateway get-resources --rest-api-id $REST_API_ID --query "items[?path=='/get-upload-url'].id" --output text)
          echo "GET_UPLOAD_URL_RESOURCE_ID is: [${GET_UPLOAD_URL_RESOURCE_ID}]"
          
          if [ -z "$GET_UPLOAD_URL_RESOURCE_ID" ]; then
            echo "::error::GET_UPLOAD_URL_RESOURCE_ID is empty. Cannot proceed."
            exit 1
          fi

          echo "Running terraform import..."
          $TF_PATH import \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            module.api.aws_api_gateway_resource.get_upload_url $REST_API_ID/$GET_UPLOAD_URL_RESOURCE_ID

      # Second Plan Step (After Imports)
      - name: Terraform Plan After Imports
        id: plan_after_imports
        run: |
          set -x
          echo "--- Plan After Imports Step ---"
          ${{ steps.verify_tf.outputs.terraform_path }} plan \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            -no-color

      - name: Terraform Apply
        id: apply
        run: |
          set -x
          echo "--- Apply Step ---"
          ${{ steps.verify_tf.outputs.terraform_path }} apply \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            -auto-approve
