# pipeline to scan terraform code.

name: 'Scan'

on: [push, pull_request]

jobs:
  gitleaks-scan:
    name: Scan for Secrets (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LEAK_EXIT_CODE: "1"

  
